feat(utils): add indicator & install pyimgur for upload img
TKU-CSIE-Project/ChivesBeacon pull request #1
Opened 2022-10-29 10:47 UTC by zous910814

2022-10-29 20:59 UTC, zous910814 commented
update indicator method to use yfinance api

2022-11-01 03:13 UTC, a5512167086 reviewed
Please add commet to explain .gitkeep file. 
ex. Add .gitkeep to keep cache folder for saving img to locale and upload to imgur API

2022-11-02 11:15 UTC, a5512167086 requested changes

2022-11-02 11:15 UTC, a5512167086 commented on src/utils/Indicator.py
> +        當日K值=前一日K值 * 2/3 + 當日RSV * 1/3
Please use English for comment message

2022-11-02 11:15 UTC, a5512167086 commented on src/utils/Indicator.py
> +        當日D值=前一日D值 * 2/3 + 當日K值 * 1/3
Please use English for comment message

2022-11-02 11:15 UTC, a5512167086 commented on src/utils/Indicator.py
> +        EMA(指數移動平均)：計算MACD時，會先計算長、短天期的指數移動平均線(EMA)
Please use English for comment message

2022-11-02 11:15 UTC, a5512167086 commented on src/utils/Indicator.py
> +        :return:
Please simplify those comments and use English too

2022-11-02 11:15 UTC, a5512167086 commented on src/utils/Indicator.py
> +        rsv = (今日收盤價 - 最近九天的最低價)/(最近九天的最高價 - 最近九天最低價)
Please use English for comment message

2022-11-02 11:15 UTC, a5512167086 commented on src/utils/Indicator.py
> +                     savefig='picture/' + str(round(data['證券代號'].values[0])) + '.png')
Add TODO for markdown we need to add UID library for making file name random
[Doc](https://blog.csdn.net/lanchunhui/article/details/61917841)

2022-11-02 11:15 UTC, a5512167086 commented on src/utils/Indicator.py
> +        if savefig == True:
Don't push debugging code on your PR, remove these condition

2022-11-02 11:15 UTC, a5512167086 commented on src/utils/Indicator.py
> +                     volume=True, mav=(5, 20, 60, 120, 240))
Don't push debugging code on your PR, remove these condition

2022-11-02 11:15 UTC, a5512167086 commented on src/utils/Indicator.py
> +            plt.show()
Don't push debugging code on your PR, remove these condition

2022-11-02 11:15 UTC, a5512167086 commented on src/utils/Indicator.py
> +            plt.show()
Don't push debugging code on your PR, remove these condition

2022-11-02 11:15 UTC, a5512167086 commented on src/utils/Indicator.py
> +            plt.show()
Don't push debugging code on your PR, remove these condition

2022-11-09 01:45 UTC, a5512167086 approved these changes
Approve

2022-11-09 01:46 UTC, merged